# Generated by Django 3.2.3 on 2021-09-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fruits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=15)),
                ('fprice', models.FloatField()),
                ('fqty', models.IntegerField()),
                ('fqlity', models.CharField(max_length=10)),
            ],
        ),
    ]
